### ISSUE TITLE
Add variable to State dosen't work

### ISSUE THREAD

**Issue by ubeydtalha** [BalaDhruv/Flutter_Redux_Gen#21]
**Describe the bug**

**To Reproduce**
1. Go to 'any_state.dart'
2. Right Click on 'state class'
3. Scroll down to 'Add new Variable'
4. Do steps
5. Dosen't work.

**Expected behavior**
It should be create new variable and adapt whole set for new variable

**Desktop :**
Version: 1.92.0 (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by chandru1117** [comment]
Thank You! This bug is fixed in 3.0.9.
