### ISSUE TITLE
Create Parent is't working

### ISSUE THREAD

**Issue by AtixD** [BalaDhruv/Flutter_Redux_Gen#6]
Create Parent is't working
In the current ver. VS code,

**Comment by AtixD** [comment]
Please check your path. Otherwise file a issue in Git Repo. Let me help.

**Comment by BalaDhruv** [comment]
Please can you elaborate on the issue?

Is Create Parent is not working?

**Comment by BalaDhruv** [comment]
Create parent is working.
I am closing the issue for now.

**Comment by shirokovroma** [comment]
Any create is not working if you have dot in username on mac. For example:
`/Users/user.name/projects/example/lib/main.dart `
will be converted to 
`/Users/projects/example/lib` - user.name lost
by [getFilePath function](https://github.com/BalaDhruv/Flutter_Redux_Gen/blob/b3732c7d947dcf8ed5c7bd1759c76892005db122/src/resources/utils/utils.ts#L10)
