### ISSUE TITLE
Any create is not working if you have dot in username on mac. 

### ISSUE THREAD

**Issue by shirokovroma** [BalaDhruv/Flutter_Redux_Gen#7]
Any create is not working if you have dot in username on mac. For example:
`/Users/user.name/projects/example/lib/main.dart `
will be converted to 
`/Users/projects/example/lib` - user.name lost
by [getFilePath function](https://github.com/BalaDhruv/Flutter_Redux_Gen/blob/b3732c7d947dcf8ed5c7bd1759c76892005db122/src/resources/utils/utils.ts#L10)

_Originally posted by @twopm in https://github.com/BalaDhruv/Flutter_Redux_Gen/issues/6#issuecomment-774516849_

**Comment by BalaDhruv** [comment]
I am fixing it.

**Comment by BalaDhruv** [comment]
The issue fixed is 3.0.0.

Closing the issue.
