### ISSUE TITLE
Cannot create parent set. Windows10

### ISSUE THREAD

**Issue by nfjdu** [BalaDhruv/Flutter_Redux_Gen#8]
**Describe the bug**
Parent set is not created after the name entered.

**To Reproduce**
1. Tap 'Create parent set'
2. Enter the name
3. Click enter
4. See an error in the console

**Expected behavior**

**Error**
Not sure, but seems like problem is with a slash before the drive volume

ERR EINVAL: invalid argument, mkdir '/C:/Users/.../Desktop/.../.../.../lib/store': Error: EINVAL: invalid argument, mkdir '/C:/Users/.../Desktop/.../.../.../lib/store'
    at mkdirSync (fs.js:925:3)
    at Object.e.mkdirSync (electron/js2c/asar_bundle.js:5:12016)
    at Object._createFolder [as createFolder] (c:\Users\vladm\.vscode\extensions\baladhruv.flutter-redux-gen-2.0.0\out\resources\utils\file-utils.js:20:12)
    at c:\Users\vladm\.vscode\extensions\baladhruv.flutter-redux-gen-2.0.0\out\extension.js:192:50

**Desktop (please complete the following information):**
 - OS: Windows10

**Additional context**

**Comment by BalaDhruv** [comment]
Can you share with me the path where do you trying to create a Parent Set?

**Comment by nfjdu** [comment]
> Can you share with me the path where do you trying to create a Parent Set?

Sent to your email, check pls.

**Comment by BalaDhruv** [comment]
Fixed the issue in 3.00.
Please check and let me know if the issue still exists.

For now, I am closing the issue.

**Comment by nfjdu** [comment]
For now, absolutely nothing happens, after clicking any of the buttons (e.g create parent set...). And no errors in the console btw

**Comment by BalaDhruv** [comment]
Can I know which operating you are using?
If you can post a small demo video that would be great.

**Comment by nfjdu** [comment]
Seems like I resolved an issue, will make a pr in several minutes (~50min)

**Comment by BalaDhruv** [comment]
Awesome, thanks!

**Comment by nfjdu** [comment]
@BalaDhruv made a pr. Check it pls. And could you please check either it works on mac or linux? Because as I mentioned in issue title , I have win10, and not sure fixes work correctly on other platforms

**Comment by BalaDhruv** [comment]
Let me check and merge the code
